name: Run Ma'at experiment

on:
  release:
    types: [ published ]
  workflow_dispatch:

jobs:
  run-maat-experiment:
    name: Run experiment workflow
    runs-on: ubuntu-latest

    steps:
      - run: gh workflow run Experiment --repo software-mansion/maat -f workspace=nightly
        env:
          GH_TOKEN: ${{ secrets.MAAT_CONTENTS_READ_ACTIONS_WRITE }}
